### ISSUE TITLE
Improve issues handling: no iteration

### ISSUE THREAD

**Issue by baranowb** [jboss-set/aphrodite#105]
Currently Aphoridte.getIssue iterates over every available tracker: https://github.com/jboss-set/aphrodite/blob/master/src/main/java/org/jboss/set/aphrodite/Aphrodite.java#L211
This does not seem the best approach. We have URLs or at least we could introduce capabilities/types

**Comment by elguardian** [comment]
Not it does not. it checks the url before using getIssue from that tracker. Each tracker knows if it can accept the url given as a parameter. What you are suggesting means to duplicate a logic is already there.

**Comment by baranowb** [comment]
Well, not quite. You create issue, or update it, but spamming all available tracker services, rather than check for one that should work. This is wrong.

**Comment by baranowb** [comment]
For instance:
for (IssueTrackerService trackerService : issueTrackers) {
            if (!trackerService.addCommentToIssue(commentMap))

**Comment by baranowb** [comment]
@elguardian : https://github.com/jboss-set/aphrodite/pull/106
