### ISSUE TITLE
Adding support for JIRA labels

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/aphrodite#124]
Unless i'm wrong, the information on JIRA labels are not exposed in any way through Aphrodite API. I would like to simply add them to the JiraIssue:

public getLabels<JiraLabel>(); // and create a JiraLabel object appropriatly

This would allow to implements the ['downstream_dependency' check in Bugclerk](https://github.com/jboss-set/bug-clerk/issues/54), but also would help us automate processes around labels.

**Comment by soul2zimate** [comment]
implemented in https://github.com/jboss-set/aphrodite/pull/129
