### ISSUE TITLE
Remove unwarranted exceptions for instance: Aphrodite.getRepository throws exception instead returning null

### ISSUE THREAD

**Issue by baranowb** [jboss-set/aphrodite#132]

**Comment by wolfc** [comment]
https://github.com/jboss-set/aphrodite/blob/2a32679a3f0223fcd5c759f4014baab0732e2a00/github/src/main/java/org/jboss/set/aphrodite/repository/services/github/GitHubRepositoryService.java#L171

**Comment by wolfc** [comment]
The top level throw within Aphrodite might not make sense, but each RepositoryService is allowed to throw a NotFoundException that can contain more context besides just url.

**Comment by baranowb** [comment]
Well, underlying SPI is just confusing, in a way:
if (responseCode == HttpURLConnection.HTTP_UNAUTHORIZED) // 401 / Unauthorized == bad creds
            throw e;

**Comment by baranowb** [comment]
It seems that our code is inline with API, lets leave it as is.
