### ISSUE TITLE
Hang due to JSONException until Jenkins job timeout.

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/aphrodite#133]
The following issue was reported on BugClerk:

_Recent bugclerk runs for jira failed due to JSONException, it seems that Jira sometimes can not return good formatted JSONObject in its response as builds in yesterday are good.

Jenkins job log https://thunder.sin2.redhat.com/jenkins/job/bugclerk-reports-jira-eap70z-unresolved/7512/console

The job is aborted until it's timeout set in Jenkins, But I think it should have some timeout value in BugClerk, so it can actively cancel it in such case.

Low priority. As Jenkins can kill it at 10 mins timeout._

(see https://github.com/jboss-set/bug-clerk/issues/56)

I will obvisouly enhanced the way Bugclerk is handling the exception, but I do think some work / thoughs need to be put into exception handling within Aphrodite. IHMO, Aphrodite should wrap those kind of exception and raise some generic one (like, in this case, something like RemoteTrackerTimeOutException)

my 2 cents.

**Comment by baranowb** [comment]
Yeah, I have this task on my head. Instead of exception, some sort of hollow issue/PR should be returned with indication of failure - most likely, a soft failure, if you will.

**Comment by baranowb** [comment]
After consideration, Im goin to close this. This will be part of refactoring effort.
