### ISSUE TITLE
Make failures a bit more transient.

### ISSUE THREAD

**Issue by baranowb** [jboss-set/aphrodite#143]
At the moment most of aphrodite code throws NFE left to right. This possibly makes no sense. For instance, if user links CVE/embargoed issue we should not throw exception, there is nothing that can be done during runtime, if issue/PR cant be found. Rather than NFE, pojos should indicate state in some way.

**Comment by rpelisse** [comment]
I agree , it is true that throwing NFE wrapping an InterruptException or an InterruptException (like in the [JiraIssueTracker](https://github.com/jboss-set/aphrodite/blob/master/jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraIssueTracker.java#L127)). On top of passing the original exception we should probably change those NFE to more appropriate exceptions (IllegalArgument or IllegalState for instance).
