### ISSUE TITLE
GITHUB API may return bad content, this results in random not checked exceptions

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/aphrodite#150]
see https://github.com/jboss-set/pull-request-processor/issues/74
Ideally we should use Optional, but this requires the API change in minor version upgrade. Maybe just check the null value for whatever reason.

**Comment by baranowb** [comment]
https://github.com/kohsuke/github-api/issues/372

**Comment by soul2zimate** [comment]
Fixed by our workaround in https://github.com/jboss-set/aphrodite/pull/151
