### ISSUE TITLE
Aphrodite does not support 'maxThread'  

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/aphrodite#152]
Due to a JSON parsing issue, maxThreadCount is always defaulted to 0 - regardless of the value set in the config file. I've modified some unit test to illustrate the issue.

**Comment by rpelisse** [comment]
This issue is hidden because of a swallowed exception in the following call:

`jsonObject.getInt("maxThreadCount", 0);`

**Comment by baranowb** [comment]
https://github.com/jboss-set/aphrodite/pull/183
