### ISSUE TITLE
Caching upstreamReferences stream causes IllegalStateException 

### ISSUE THREAD

**Issue by spyrkob** [jboss-set/aphrodite#156]
https://github.com/jboss-set/aphrodite/blob/master/jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraIssue.java#L119-L121

If a terminal operation is called on this stream, it will be closed and an exception will be thrown on next usage.

**Comment by soul2zimate** [comment]
Fixed in https://github.com/jboss-set/aphrodite/pull/157
