### ISSUE TITLE
possible IllegalStateException: stream has already been operated upon or closed

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/aphrodite#164]
In updating an existing issue in payload, https://github.com/jboss-set/aphrodite/blob/aphrodite-0.7.2.Final/jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/JiraIssue.java#L118 causes **_IllegalStateException: stream has already been operated upon or closed_**
Because same stream has been already operated on the first call.

It should always call super.getUpstreamReferences() to return a new stream to operate on, otherwise, it should return a collection instead.

**Comment by wolfc** [comment]
A `Stream` must never be cached.

**Comment by soul2zimate** [comment]
Fixed in https://github.com/jboss-set/aphrodite/pull/165
