### ISSUE TITLE
PatchesHome is implemented in jboss-set/assitant

### ISSUE THREAD

**Issue by baranowb** [jboss-set/aphrodite#193]
Fetch patches was supposedly unreliable. Code has been reworked, but PatchesHome impl is not part of aphrodite. It is in :: https://github.com/jboss-set/assistant/blob/master/src/main/java/org/jboss/set/assistant/PatchHomeService.java

Similarly there is https://github.com/jboss-set/assistant/blob/master/src/main/java/org/jboss/set/assistant/IssueHomeService.java  
Duplicate of JiraIssueHomeImpl ?

**Comment by soul2zimate** [comment]
Open https://github.com/jboss-set/aphrodite/pull/194 for PatchesHome impl
And yes, IssueHomeService.java is duplicate, will be removed in assistant with Aphrodite new upgrade.
