### ISSUE TITLE
Can't use as a dependency

### ISSUE THREAD

**Issue by jeffmaury** [jboss-set/aphrodite#204]
I tried to bootstrap a Maven project but got the following error:

`
[ERROR] Failed to execute goal on project issuelint: Could not resolve dependencies for project org.example:issuelint:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.jboss.set:aphrodite:jar:0.4.1 -> com.atlassian.jira:jira-rest-java-client-api:jar:3.0.0: Failed to read artifact descriptor for com.atlassian.jira:jira-rest-java-client-api:jar:3.0.0: Could not transfer artifact com.atlassian.jira:jira-rest-java-client-api:pom:3.0.0 from/to repository.engineering.redhat.com (https://repository.engineering.redhat.com/nexus/content/groups/eng-ops-public/): repository.engineering.redhat.com: Unknown host repository.engineering.redhat.com -> [Help 1]`

Also the doc is not quite clear as seems there are more recent versions than `0.4.1`

**Comment by soul2zimate** [comment]
Hi, there was a module split long time ago, so the configuration in the README is out of date. I have corrected it in the master branch. The latest released version is 0.7.9.Final.
