### ISSUE TITLE
Add Status API usage

### ISSUE THREAD

**Issue by wolfc** [jboss-set/aphrodite#21]
https://developer.github.com/v3/repos/statuses/

**Comment by elguardian** [comment]
out of curiosity... what did you have in mind when you proposed this feature ? what's the purpose ?

**Comment by ryanemerson** [comment]
@elguardian It is so that applications, such as pull-processor, can tell whether a PRs CI builds have been successful.

**Comment by elguardian** [comment]
@ryanemerson I thought that was something done by teamcity hook already. 
https://github.com/JetBrains/commit-status-publisher ?

**Comment by ryanemerson** [comment]
@elguardian I haven't looked into that library properly, but I think that is for setting the status.  For Aphrodite the focus would be simply retrieving the status and incorporating it into the Patch object so that the using app can instigate an appropriate course of action.

**Comment by ryanemerson** [comment]
@elguardian The GH library we use may already have support for this, I just haven't looked into it yet.

https://github.com/eclipse/egit-github/tree/master/org.eclipse.mylyn.github.core

**Comment by elguardian** [comment]
ah ok. now I understand. I thought it was more like setting the status of the commit given the ack flags status.

**Comment by ryanemerson** [comment]
@elguardian I think for that we can continue to use labels via [addLabelToPatch](https://github.com/jboss-set/aphrodite/blob/master/src/main/java/org/jboss/set/aphrodite/spi/RepositoryService.java#L107-#L115) like we do in the EAP repos

**Comment by soul2zimate** [comment]
this can be achieved by CommitService and CommitStatus
