### ISSUE TITLE
clarification of goals

### ISSUE THREAD

**Issue by maxandersen** [jboss-set/aphrodite#210]
i became aware of this repo in conversations around how to best link up jira and github issues but from the docs and code i'm not sure if this is what aphrodite is meant to help with.

Two questions:

* What is "SET issues" ? 
* I can get bugzilla and jira issues but didn't see a way to get github issues...is that intentional ?

**Comment by soul2zimate** [comment]
@baranowb  ^

**Comment by baranowb** [comment]
SET issues  - where does this come from? Most likely issues that SET is supposed to take care of

github issues are out of scope, as we, nor upstream use those.
