### ISSUE TITLE
[request] Add a method to create a Jira issue

### ISSUE THREAD

**Issue by cmoulliard** [jboss-set/aphrodite#217]
## Request

The existing project dont allow to create a Jira issue as atlassian jira java lib proposes

https://docs.atlassian.com/jira-rest-java-client-parent/4.0.0/apidocs/com/atlassian/jira/rest/client/api/IssueRestClient.html#createIssue(com.atlassian.jira.rest.client.api.domain.input.IssueInput)

. That should be great that Aphrodite offers such a feature too ;-)

**Comment by baranowb** [comment]
Issue issue = aphrodite.createIssue(new URL("https://issues.redhat.com"), "TEST", new String[] {"DASTAN!!!","2"});
https://issues.redhat.com/browse/TEST-973
Issue issue = aphrodite.createIssue(new URL("https://bugzilla.redhat.com"), "JBoss Enterprise Application Platform 6", new String[] {"NCC-1701-D","Documentation","TBD EAP 6"});
https://bugzilla.redhat.com/show_bug.cgi?id=1877734

**Comment by baranowb** [comment]
Merged.
