### ISSUE TITLE
Adding resoultionDate

### ISSUE THREAD

**Issue by rstancel** [jboss-set/aphrodite#227]
I am trying to add a resoultionDate but it seems it was removed from atlassian API. See this: https://github.com/rstancel/aphrodite/commit/d1e31cd80ae5824680f8a1b6477108635851f546#diff-3511e058052f770e441e3c22939ceef1R101-R102

**Comment by rstancel** [comment]
@baranowb FYI

**Comment by baranowb** [comment]
https://bitbucket.org/atlassian/jira-rest-java-client/src/jira-rest-java-client-parent-5.2.1/api/src/main/java/com/atlassian/jira/rest/client/api/domain/IssueFieldId.java  REST client never had one, so it does not parse it it seems.

**Comment by fazer1929** [comment]
There seems to be no way of **setting the resolution date in the JIRA API**.  According to the Atlassian team resolution data is final and shall not be changed.  
[This is the link to the question](https://community.atlassian.com/t5/Jira-questions/Is-there-an-API-to-get-a-close-date-of-an-issue/qaq-p/1082253)
