### ISSUE TITLE
JIRA update logic doesn't support time estimates anymore

### ISSUE THREAD

**Issue by ryanemerson** [jboss-set/aphrodite#23]
This used to work ... 

May need to rewrite update function so that is a direct REST call

**Comment by elguardian** [comment]
updating with JIRA library.

there is a problem with estimates.... you cannot log hours spent. you can only set estimates. If you try to do an update it will throw an error. (it happens the same problem with the reportee, it is not possible to modify it directly).

**Comment by ryanemerson** [comment]
@elguardian Can it not be accomplished via one of the methods specified in comment 1?

https://jira.atlassian.com/browse/JRA-33749

**Comment by elguardian** [comment]
it is not the same field... but I can give a try.

**Comment by ryanemerson** [comment]
https://github.com/jboss-set/aphrodite/commit/8a1c6d18be523af0a2fb8eac53f3518cdbe3bac3

I have removed the existing update logic todo with "originalEstimate" as this code causes an update operation to always returns a http 400 code. It seems that JIRA time estimates now need to be updated using [JIRA worklogs] (https://docs.atlassian.com/jira/REST/latest/#api/2/issue-updateWorklog).

**Comment by baranowb** [comment]
No longer relevant.
