### ISSUE TITLE
Jira Issue tracker implementation does not support concurrency

### ISSUE THREAD

**Issue by elguardian** [jboss-set/aphrodite#25]
In order to speed up jira processing, concurrency is needed. At present if you try to use it
concurrently it raises an exception

**Comment by ryanemerson** [comment]
@elguardian Thanks for raising the issue. The underlying JiraClient object (third party) used by Aphrodite is not  threadsafe, so I assume this will be the cause of the issues.  Do you have a reproducer/example use case for when such an exception is raised?

**Comment by elguardian** [comment]
I have push the code to my fork https://github.com/elguardian/pull-request-processor

the class I mentioned in IRC
https://github.com/elguardian/pull-request-processor/blob/master/src/main/java/org/jboss/pull/processor/AphroditeUtil.java

**Comment by elguardian** [comment]
it is going to be fixed by https://github.com/jboss-set/aphrodite/issues/33
