### ISSUE TITLE
Stream flag status not working for JIRA

### ISSUE THREAD

**Issue by elguardian** [jboss-set/aphrodite#30]
Not working. Cannot get the information about the flags in JIRA. does it exist ?

**Comment by ryanemerson** [comment]
@elguardian When I implemented this part of the code, there was no stream flag on the JIRAs (and still isn't).  Now the process is to set the Stream in the Target Release field of the JIRA, so when I get a chance I will update the code to get the Stream from said field.

**Comment by elguardian** [comment]
this is done already. There is a difference with BZ with #33 
· Stream flag = target release
· Release = versions fixed
