### ISSUE TITLE
java.lang.NullPointerException  at org.jboss.set.aphrodite.issue.trackers.bugzilla.IssueWrapper.bugzillaBugToIssue

### ISSUE THREAD

**Issue by bayern39** [jboss-set/aphrodite#37]
when i want get issue from the bugzila,it has a error "NullPointerException" .it happened  in  "issue.setEstimation",because the "estimatedTime" and "hoursWorked" is null,as we konw,we can not assign null to the java basic type. i want add the judgement whether the field is null.

**Comment by elguardian** [comment]
It could be null. This also happens in Jira so I don't see a problem with this.

**Comment by ryanemerson** [comment]
I think this is a bug, as it is better for the user to make use of the Issue.getEstimation() optional return type if the issueEstimation is null opposed to a NullPointerException being thrown.

**Comment by elguardian** [comment]
I'm closing this

**Comment by ryanemerson** [comment]
@elguardian I'm re-opening this as @bayern39 is redoing the PR and he is updating the title and commit message to reference this issue. It makes sense for the commit history to reference issues when they exist. Especially in this case where the issue provides more information.
