### ISSUE TITLE
patch search based on issue id on GitHub is not accurate

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/aphrodite#74]
current aphrodite.getPatchesAssociatedWith() is general search on whole GitHub, it can get false result for instance:

```
Issue issue = aphrodite.getIssue(new URL("https://bugzilla.redhat.com/show_bug.cgi?id=1305960"));
List<Patch>  patches = aphrodite.getPatchesAssociatedWith(issue);
```

https://github.com/centrifugal/centrifugo/pull/84 is in the list because id "1305960" matched one of commit sha code.

It should allow to specify target repositories defined in streams.

**Comment by wolfc** [comment]
Patches should not be obtained out of the repository services, because they are tied directly to an issue.

**Comment by baranowb** [comment]
Fixed at some point.

**Comment by baranowb** [comment]
https://github.com/jboss-set/aphrodite/blob/master/domain/src/main/java/org/jboss/set/aphrodite/domain/Issue.java#L99  - this is never used.
