### ISSUE TITLE
Bugzilla issue misses field "External Trackers"

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/aphrodite#79]
Bugzilla field "External Trackers" is needed as it allows to obtain upstream issue link.

**Comment by elguardian** [comment]
I think the best way is to implement this is to add to the dependencies field instead of create a new one. It fits the logic and domain behind aphrodite.

**Comment by soul2zimate** [comment]
Fine by me, one exception is that we also put "Red Hat Customer Portal" case in this field.
I don't think there is anything we need to collect from customer case by now, although it's a bit odd to map it as an Aphrodite issue. Maybe it should be ignored.

**Comment by elguardian** [comment]
getting bad.... https://bugzilla.redhat.com/docs/en/html/api/extensions/ExternalBugs/lib/WebService.html
I don't see a clear way to retrieve that ... the service Bug.get (XMLRPC) doest not retrieve the field either. 

{code}
curl --silent --insecure   https://bugzilla.redhat.com/xmlrpc.cgi   -H "Content-Type: text/xml"   -d "<?xml version='1.0' encoding='UTF-8'?><methodCall><methodName>Bug.fields</methodName> <params> <param><value><struct><member><name>ids</name><value>6941</value></member></struct></value></param> </params> </methodCall>"   | tidy -xml -indent -quiet
<?xml version="1.0" encoding="utf-8"?>
{code}

**Comment by soul2zimate** [comment]
The ancient pull-shared used field name "external_bugs"
https://github.com/jboss-set/pull-shared/blob/master/src/main/java/org/jboss/pull/shared/connectors/bugzilla/Bug.java#L130 as defined inside https://bugzilla.redhat.com/docs/en/html/api/Bugzilla/WebService/Bug.html

**Comment by elguardian** [comment]
I was looking the wrong way... that works. thx

**Comment by elguardian** [comment]
pushed  https://github.com/jboss-set/aphrodite/pull/82

**Comment by soul2zimate** [comment]
I merged https://github.com/jboss-set/aphrodite/pull/82
thanks,
