### ISSUE TITLE
Add AffectedVersion to Issue and clarify distinction with releases

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/aphrodite#90]
In both JIRA and Bugzilla, there is a notion of "affected versions". For Bugzilla, the field is simply called "version" and can be set to several values. For instance, in [BZ1282660](https://bugzilla.redhat.com/show_bug.cgi?id=1282660), the affected version is 6.4.4.

In JIRA, the field is appropriatly named "Affected Versions", and, for instance, in [JBEAP-783](https://issues.jboss.org/browse/JBEAP-783) the affected version is 7.0.0.DR8. 

Currently, the API proposed by Aphrodite is exposing this information - which is semantically the same, through *two different fields*:
* the version - which is buzgilla is the equivalent of JIRA's affected version, and
* the version part of the Release object

So depending on the nature of the bug (JIRA or Bugzilla) you need to access the information differently. Which, IMHO, defeats the point of having Aphrodite providing an abstraction layer.

To solve that, this PR adds an AfffectedVersion (List) to the Issue itself. For a bug coming from Bugzilla, this list will contains the value associated with the 'version' field, and for JIRA the content of the affectedVersion field.

This way, there will be one, same approach to fetch this information, regardless of the nature of the bug.

**Comment by rpelisse** [comment]
https://github.com/jboss-set/aphrodite/pull/91

**Comment by baranowb** [comment]
Fixed via: https://github.com/jboss-set/aphrodite/pull/101
